---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argo-applications"
  namespace: continious-delivery
spec:
  project: default
  source:
    repoURL: "https://github.com/istimaldar-test/productivity-environment.git"
    targetRevision: HEAD
    path: charts/argo-application
    helm:
      valueFiles:
        - ../../values/argo-application.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: continious-delivery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

