{{-  range .Values.applications }}
{{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  labels:
    {{- include "argo-application.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: {{ .repo | quote }}
      targetRevision: {{ .version | quote }}
      chart: {{ .chart | quote }}
      helm:
        valueFiles:
          - "$values/values/{{ .name }}.values.yaml"
    - repoURL: {{ $.Values.settingsRepo | quote }}
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
{{- end }}
{{- end }}